### PR TITLE
fix migrator

### PR DESCRIPTION
**Pull request by jayfurmanek**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #5

### CODE REVIEW

**Comment by jayfurmanek** [comment]
@conda-forge-admin, please rerender

**Comment by jayfurmanek** [comment]
needs https://github.com/conda-forge/libogg-feedstock/pull/8

**Review by xhochy — APPROVED** [review]

**Comment by jayfurmanek** [comment]
hmmm. The aarch64 final build didn't show up.
https://anaconda.org/conda-forge/libflac/files

@xhochy Is there a way to check (or rekick) the publish build on drone?

**Comment by jakirkham** [comment]
Thanks for letting us know. 🙂

We have been experiencing some issues with Drone ( https://github.com/conda-forge/conda-forge.github.io/issues/954 ). Prodded Drone, which seems to have got the build going. Please let us know whether that fixes it or not.

**Comment by jayfurmanek** [comment]
That worked!

**Pull request merged**
