### PR TITLE
Release 1.3.3

### LINKED ISSUE #7: Could NOT find FLAC (missing: FLAC_LIBRARY) on Windows
When building a cmake project that depends on libflac, I get a `Could NOT find FLAC (missing: FLAC_LIBRARY)` on Windows (Linux and OSX seems to be finding libflac correctly).

Looking at the recipe I see there is a custom CMakeList file.

I feel like this issue is related to the one in libvorbis package, I see you are listed as a maintainer @dschreij. Would you like me to try using the official CMakeList file for Windows? I'm happy to do it tonight.

### PR DESCRIPTION
**Pull request by martinRenou**
Signed-off-by: martinRenou <martin.renou@gmail.com>

Fixes #7 

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by martinRenou** [comment]
@conda-forge-admin, please rerender

**Comment by martinRenou** [comment]
Fixes #7

**Comment by martinRenou** [comment]
@dschreij This one should be ready for a review :)

**Review by dschreij — APPROVED** [review]
Looks good! Thanks for all the hard work. If it builds then I see no further reasons to hold this back.

**Comment by martinRenou** [comment]
Thanks a lot for merging!

**Pull request merged**
